---
- name: Deploy app
  hosts: apps
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Clone repository
      git:
        repo: https://github.com/Nishke-Paz/project-for-ansible.git
        dest: home/user/web-app

    - name: Install app dependencies
      command: npm install
      args:
        chdir: home/user/web-app

    - name: Start app
      command: node index.js
      args:
        chdir: home/user/web-app
